package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginAndSignUp
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        btniniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btncrearcuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setMinimumSize(new java.awt.Dimension(400, 500));

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));
        JPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        JPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setMinimumSize(new java.awt.Dimension(400, 500));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\Sena- Tecnologo\\SEAFOOD-TRACKER-BRAME\\SeaFood-Tracker-Brame\\src\\main\\java\\Images\\Logo Surticarnes Brame.png")); // NOI18N
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel5.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel5.setPreferredSize(new java.awt.Dimension(400, 400));
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        JPanel1.add(Right);
        Right.setBounds(0, 0, 400, 500);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JPanel1.add(Left);
        Left.setBounds(400, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("INICIAR SESION");
        JPanel1.add(jLabel1);
        jLabel1.setBounds(470, 20, 280, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("USUARIO:");
        JPanel1.add(jLabel2);
        jLabel2.setBounds(430, 110, 70, 20);

        id_usuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JPanel1.add(id_usuario);
        id_usuario.setBounds(430, 130, 330, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");
        JPanel1.add(jLabel3);
        jLabel3.setBounds(430, 220, 120, 20);

        contrasena.setMinimumSize(new java.awt.Dimension(64, 28));
        JPanel1.add(contrasena);
        contrasena.setBounds(430, 240, 330, 40);

        btniniciar.setBackground(new java.awt.Color(0, 102, 102));
        btniniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btniniciar.setForeground(new java.awt.Color(255, 255, 255));
        btniniciar.setText("Iniciar Sesión");
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });
        JPanel1.add(btniniciar);
        btniniciar.setBounds(520, 310, 150, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No tengo una cuenta");
        JPanel1.add(jLabel4);
        jLabel4.setBounds(430, 380, 150, 40);

        btncrearcuenta.setBackground(new java.awt.Color(0, 102, 102));
        btncrearcuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncrearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        btncrearcuenta.setText("Crear cuenta");
        btncrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearcuentaActionPerformed(evt);
            }
        });
        JPanel1.add(btncrearcuenta);
        btncrearcuenta.setBounds(590, 390, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
                // System.out.println("Sign up btn clicked");
        int Id_usuarioInt = 0;        
        String  Contrasena, fname = null, passDb = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/bramestockmanager";
        SUser = "root";
        SPass = "Salamanc@2117";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            if("".equals(id_usuario.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Ingresa el usuario", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if(new String(contrasena.getPassword()).equals("")){
                JOptionPane.showMessageDialog(new JFrame(), "Ingresa la contraseña", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else {

            try {
                Id_usuarioInt = Integer.parseInt(id_usuario.getText().trim()); // Convertir a int
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(new JFrame(), "ID de usuario no válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Contrasena    = new String(contrasena.getPassword());
            
            PreparedStatement ps = con.prepareStatement("SELECT * FROM usuarios WHERE id_usuario = ?");
            ps.setInt(1, Id_usuarioInt); // Usar setInt ya que id_usuario es int en la BD
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                passDb = rs.getString("contrasena");
                fname = rs.getString("id_usuario");
            }
            if( new String(contrasena.getPassword()).equals(passDb)){
                Inicio InicioFrame = new Inicio();
                InicioFrame.setVisible(true);
//                LoginFrame.pack();
                InicioFrame.setLocationRelativeTo(null);
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(new JFrame(), "ID o contraseña incorrectas", "Error",
                        JOptionPane.ERROR_MESSAGE);
               
            }
            
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        } 
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btncrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearcuentaActionPerformed
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_btncrearcuentaActionPerformed

    /**
     * @param args the command line arguments
     */   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JButton btncrearcuenta;
    private javax.swing.JButton btniniciar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField id_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
